server:
  port: 6969

spring:
  application:
    name: Identity-Service

#    For email services

  mail:
    host: smtp.gmail.com
    port: 587
    username: avarmittal1sep@gmail.com
    password: hgrtnrjqwdorexdh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#How to put password and username from enviroment ???
  datasource:
#    url: jdbc:mysql://localhost:3306/socials_user
    url: jdbc:mysql://mysql-db:3306/socials_user
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://naming-server-service:8761/eureka
      #      defaultZone: http://localhost:8765/eureka